UNITS = 256 # Transformer
# Transformer
NUM_BLOCKS = 4
MLP_RATIO = 2

# Dropout
EMBEDDING_DROPOUT = 0.00
MLP_DROPOUT_RATIO = 0.30
CLASSIFIER_DROPOUT_RATIO = 0.10

# N_EPOCHS = 150
batch_size = 32
N_EPOCHS = 200
LR_MAX = 1e-4
N_WARMUP_EPOCHS = 0
WD_RATIO = 0.05
NUM_CLASSES = 250