artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/emergency/data_ingestion
  source_URL: https://drive.google.com/drive/folders/1jtnmHKppYZhMRV0cBWEMYaccAvwkhYfj?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/emergency/data_ingestion

landmarks_extraction:
  root_dir: artifacts/emergency/data_ingestion/data
  com_dir: artifacts/emergency/landmarks_extraction
